### ISSUE TITLE
Add CSS Override Section.

### ISSUE THREAD

**Issue by XAMPPRocky** [janbaudisch/zola-sam#1]
Hello, thank you for this template! I'm using it for a site, and I noticed there's no convienvient way to inject my own style overrides to the template easily without copying a lot of the files. It would be nice if `base.html` had a section for me to be able to add CSS files.

**Comment by janbaudisch** [comment]
Would it be enough for you to just have a config option to include css files? I would prefer this option, instead of allowing inline CSS.

**Comment by XAMPPRocky** [comment]
@janbaudisch Sorry I was unclear, what I would like is a block after your stylesheets, and then I could I add `link` and `script` tags as I need. Generally it would be nice to be able to easily add elements to the `head` of a document. e.g.
```html
{% block head_content %}
<link rel="stylesheet" href="myStyles.css">
<script src="myScript.js"></script>
{% endblock %}
```

**Comment by janbaudisch** [comment]
I tried to work on it [but found a problem along the way](https://zola.discourse.group/t/tera-block-inheritance-when-modifying-a-theme/229). This has to wait until that is resolved.

**Comment by janbaudisch** [comment]
Please take a look at #2.

There is an issue (getzola/zola#361) which makes using blocks like this quite unergonomic. Basically, you would have to declare your custom head in every template. And for this theme, I want to keep it easy to use.

If you also want to use scripts, that functionality could be added in the same way as the stylesheets, although this theme is intended to be usable without any JavaScript. But I would be open to add that if needed.

So if you are ok with the approach in mentioned PR, I would merge it.

**Comment by janbaudisch** [comment]
Closing as getzola/zola#361 got resolved.
