### ISSUE TITLE
Sort sections by date

### ISSUE THREAD

**Issue by ThibaultLemaire** [janbaudisch/zola-sam#12]
I noticed posts are not sorted by date, I glanced at the code but couldn't find the relevant section, so this is just a guess but I think they're sorted by file names currently?

**Comment by mukul-mehta** [comment]
@ThibaultLemaire @janbaudisch Is there a fix for this? It would be great to be able to sort by date

**Comment by mukul-mehta** [comment]
Sorry my bad. It's a very simple fix and it depends on Zola itself and not the theme. To sort by a specific property, add the `sort = FIELD` in `_index.md`. I've set it to `sort = "date"`

https://www.getzola.org/documentation/content/section/

**Comment by janbaudisch** [comment]
Thanks @mukul-mehta for the solution.

**Comment by ThibaultLemaire** [comment]
Thanks @mukul-mehta! I can't believe I didn't find this piece of documentation myself when investigating this.
