### ISSUE TITLE
No support for subsections

### ISSUE THREAD

**Issue by therner** [janbaudisch/zola-sam#3]
Hello. I really like this template, but when I started using it, I realized it doesn't support subsections natively. I've added it for myself locally and thought it might be a cool feature to add to the theme. Here's what I've come up with where 'sub' and 'subsection' are both subsections of the section 'sample'. My graphic design skills are fairly weak, so feel free to suggest any changes if you feel that it's worth adding. I can create a PR as well if you want to take a look at my template changes.

![screenshot](https://user-images.githubusercontent.com/52645612/70854354-0793df00-1e80-11ea-95b3-4929e0d75614.png)

**Comment by janbaudisch** [comment]
Looks good!
I didn't really design this theme (it's just a port of [victoriadrake/hugo-theme-sam](https://github.com/victoriadrake/hugo-theme-sam)), so I don't have much to say regarding the design. But as far as I am concerned, it looks like a well fitting addition.
So feel free to open a PR, I will take a look at it.

**Comment by janbaudisch** [comment]
Fixed in #4.
