### ISSUE TITLE
If no footer is set, the bottom menu is squished against the bottom of the page

### ISSUE THREAD

**Issue by yvrhdn** [janbaudisch/zola-sam#6]
First of all, I'm really liking this theme. I'm looking forward to making this my main blog.

I noticed that when you don't specify a footer, the bottom menu is squished against the bottom of the page.

The following screenshots are both scrolled all the way to the bottom of the page:

- with a footer:

<img width="1339" alt="Screenshot 2020-02-15 at 21 14 13" src="https://user-images.githubusercontent.com/7748404/74594578-68829380-5038-11ea-8763-60203a8eb11b.png">

- without footer:

<img width="1339" alt="Screenshot 2020-02-15 at 21 13 38" src="https://user-images.githubusercontent.com/7748404/74594581-6fa9a180-5038-11ea-8137-9a06188edf10.png">

I think it would look nicer if the bottom menu would have some padding-bottom when no footer is set.
Is this something you would consider a PR for?

**Comment by yvrhdn** [comment]
FYI, I fixed this be shifting the padding between `.bottom-menu` and `.footer`.
See https://github.com/kvrhdn/zola-sam/commit/5470956bd879b950712d2cabd685b3c9fb157515

**Comment by janbaudisch** [comment]
Those changes look good, feel free to open a PR.
